//! The authoritative component table behind `component-inventory.json` and
//! the gallery sheets. Mirrors `docs/MASCOT_UI_COMPONENT_INVENTORY_V0.1.md`:
//! names and order are the doc's, Tier A = implemented, Tier B = planned
//! (not implemented), Tier C = deferred.

/// Sizing class per the inventory doc §2.
#[derive(Clone, Copy, PartialEq)]
pub enum Sizing {
    /// Fixed discrete size(s) — never stretched.
    Fixed,
    /// Sized by content (label length).
    ContentSized,
    /// Stretches in at least one axis across the design range.
    Stretchable,
}

impl Sizing {
    pub fn name(self) -> &'static str {
        match self {
            Sizing::Fixed => "fixed",
            Sizing::ContentSized => "content-sized",
            Sizing::Stretchable => "stretchable",
        }
    }
}

/// Gallery implementation status.
#[derive(Clone, Copy, PartialEq)]
pub enum Status {
    Implemented,
    /// Tier B — approved next, NOT implemented.
    Planned,
    /// Tier C — out of scope.
    Deferred,
}

impl Status {
    pub fn name(self) -> &'static str {
        match self {
            Status::Implemented => "implemented",
            Status::Planned => "planned",
            Status::Deferred => "deferred",
        }
    }
}

/// One inventory row.
pub struct Entry {
    /// Machine key for code lookups and file stems ("icon-button", ...).
    pub key: &'static str,
    /// Component name exactly as in the inventory doc.
    pub name: &'static str,
    /// 'A' | 'B' | 'C'
    pub tier: char,
    pub status: Status,
    pub sizing: Sizing,
    /// States rendered on the theme sheets.
    pub states: &'static [&'static str],
    /// shadcn analogue docs slug (e.g. "button"), if a direct analogue exists.
    pub shadcn: Option<&'static str>,
    /// Required when `shadcn` is None.
    pub no_analogue_reason: &'static str,
    /// Intentional deviations, one item per string (visual-review text).
    pub deviations: &'static [&'static str],
    /// Motion contract line (see design-system §2 shadcn-first motion rule).
    pub motion: &'static str,
}

/// The complete inventory: Tier A in doc order, then B (planned) and C
/// (deferred) in doc order.
pub const COMPONENTS: &[Entry] = &[
    // ---- Tier A -------------------------------------------------------
    Entry {
        key: "surface",
        name: "Surface / Bubble",
        tier: 'A',
        status: Status::Implemented,
        sizing: Sizing::Stretchable,
        states: &["plain", "focused"],
        shadcn: Some("card"),
        no_analogue_reason: "",
        deviations: &[
            "Shadow: one composited Direct2D shadow (blur sigma 4 DIP, +4 DIP y offset, 14 % alpha light / 30 % dark) instead of card shadow-sm (0 1px 3px / 0 1px 2px -1px at 10 %) — the bubble floats over arbitrary desktop content through a transparent DirectComposition window and needs stronger separation.",
            "Bare container: no CardHeader/CardContent/CardFooter slots and no 24 px card padding; Composer and Response own their insets.",
            "Radius 14 DIP, 1 DIP border (border token) and card fill match card (14 px, 1 px, #E5E5E5 / #FFFFFF; dark #171717, white 10 %).",
        ],
        motion: "none (no shadcn motion for this use)",
    },
    Entry {
        key: "typography",
        name: "Typography / Label",
        tier: 'A',
        status: Status::Implemented,
        sizing: Sizing::ContentSized,
        states: &["body", "muted", "label", "caption", "tooltip"],
        shadcn: Some("typography"),
        no_analogue_reason: "",
        deviations: &[
            "Font: Segoe UI Variable Text (native system font per the design system) instead of Geist; glyph widths differ slightly.",
            "Body is 14/400 vs shadcn typography p 16/28: the floating shell uses control text size (text-sm, as Input/Textarea/Button) for running text.",
            "Muted is 12/400 vs shadcn muted 14/20: Mascot's muted is the caption size (text-xs, as Badge/Tooltip). Colour matches muted-foreground (#737373 / #A1A1A1).",
            "Label 14/500 matches shadcn small (14/500); line height is DirectWrite natural rather than leading-none.",
        ],
        motion: "none (no shadcn motion for this use)",
    },
    Entry {
        key: "icon",
        name: "Icon",
        tier: 'A',
        status: Status::Implemented,
        sizing: Sizing::Fixed,
        states: &["16 DIP"],
        shadcn: None,
        no_analogue_reason: "shadcn has no icon component; the canonical reference is the \
                             upstream Lucide set (mascot-icons/source/ provenance)",
        deviations: &[
            "Upstream Lucide 0.544.0 geometry converted at build time to Direct2D paths (no SVG parser or icon font at runtime).",
            "16 DIP viewport, stroke-width 2 in the 24-unit art box, round caps/joins, current foreground colour — same as lucide-react at size-4.",
        ],
        motion: "none (no shadcn motion for this use)",
    },
    Entry {
        key: "icon-button",
        name: "IconButton",
        tier: 'A',
        status: Status::Implemented,
        sizing: Sizing::Fixed,
        states: &["default", "hover", "pressed", "focus-visible", "disabled"],
        shadcn: Some("button"),
        no_analogue_reason: "",
        deviations: &[
            "No outline icon button: Mascot uses primary 32 DIP (Send/Stop) and ghost 28 DIP (Copy) instead of shadcn's 36 px size-icon (outline in the example) — compact sizes that fit the 52 DIP single-line composer.",
            "Disabled uses explicit muted fill + muted-foreground icon instead of disabled:opacity-50 (one flat colour pair, no Direct2D opacity layer).",
            "Pressed is an extra state (stronger accent mix); shadcn defines no pressed treatment.",
            "Focus-visible matches shadcn: 3 DIP ring at 50 % alpha + 1 DIP ring-coloured border.",
            "Pressed (an extra native state) uses the same 150 ms transition.",
        ],
        motion: "transition-all: fill, foreground, focus ring 150 ms cubic-bezier(0.4, 0, 0.2, 1), both directions (shadcn button.tsx)",
    },
    Entry {
        key: "button",
        name: "Button",
        tier: 'A',
        status: Status::Implemented,
        sizing: Sizing::ContentSized,
        states: &[
            "default",
            "secondary",
            "ghost",
            "disabled",
            "focus-visible",
            "hover",
            "pressed",
        ],
        shadcn: Some("button"),
        no_analogue_reason: "",
        deviations: &[
            "Default fill is primary #171717 / #E5E5E5 from the documented shadcn neutral theme (ui.shadcn.com/docs/theming); the live /view examples currently render primary as #000000 in light.",
            "Compact sizes only: sm (32) and default (36); no lg or icon sizes, no outline/link/destructive variants (no product surface needs them).",
            "Disabled uses explicit muted fill + muted-foreground text instead of disabled:opacity-50.",
            "Pressed is an extra state; focus-visible ring matches shadcn (3 DIP ring/50 + 1 DIP ring border).",
            "Pressed (an extra native state) uses the same 150 ms transition.",
            "Width differs from the reference only by glyph metrics (Segoe UI Variable vs Geist), e.g. \"Secondary\" 98 vs 102 px; height, padding and radius match.",
        ],
        motion: "transition-all: fill, foreground, focus ring 150 ms cubic-bezier(0.4, 0, 0.2, 1), both directions (shadcn button.tsx)",
    },
    Entry {
        key: "tooltip",
        name: "Tooltip",
        tier: 'A',
        status: Status::Implemented,
        sizing: Sizing::ContentSized,
        states: &["shown"],
        shadcn: Some("tooltip"),
        no_analogue_reason: "",
        deviations: &[
            "Size matches (28 DIP high, 6/12 padding, 8 DIP radius, 12/400); colours match shadcn foreground/background (#0A0A0A/#FFFFFF, dark #FAFAFA/#0A0A0A).",
            "No arrow.",
            "Single line, bounded at 240 DIP with an end ellipsis; the shadcn tooltip wraps.",
            "Open delay 500 ms (Windows hover-tooltip convention) vs shadcn TooltipProvider delayDuration 0 — intentional interaction deviation; the open/close animation matches shadcn.",
            "Hover only: no keyboard-focus tooltip (Radix also opens on focus); unchanged in this pass.",
            "Transform origin is the pill's bottom centre; shadcn's is its arrow tip (no arrow here).",
        ],
        motion: "open: fade 0→1, scale 0.95→1, slide 8 DIP; close: fade→0, scale→0.95; 150 ms ease (shadcn tooltip.tsx / tw-animate-css)",
    },
    Entry {
        key: "composer",
        name: "Native Text Input / Composer",
        tier: 'A',
        status: Status::Implemented,
        sizing: Sizing::Stretchable,
        states: &[
            "empty",
            "focused",
            "text",
            "selection",
            "multiline",
            "overflow",
            "submitting",
        ],
        shadcn: Some("textarea"),
        no_analogue_reason: "",
        deviations: &[
            "The composer is the rounded bubble (14 DIP radius, composited shadow) holding a windowless RichEdit and the Send icon button, not a bordered textarea (8 px radius, shadow-xs, transparent fill).",
            "Single line is 52 DIP high and grows to 6 lines (152 DIP) then scrolls, vs textarea min-h-16 (64 px) with field-sizing-content.",
            "Focus turns the 1 DIP border ring-coloured (as shadcn border-ring) without the 3 px ring/50 halo, which would spill outside the bubble and under the mascot.",
            "No disabled state; the nearest state is submitting: editor read-only with dimmed text and Send replaced by Stop.",
            "Text 14/400 with a 20 DIP line matches textarea md:text-sm; Enter submits, Shift+Enter inserts a newline.",
        ],
        motion: "none — focus border colour changes instantly, as shadcn transition-[color,box-shadow] excludes border-color",
    },
    Entry {
        key: "separator",
        name: "Separator",
        tier: 'A',
        status: Status::Implemented,
        sizing: Sizing::Stretchable,
        states: &["horizontal"],
        shadcn: Some("separator"),
        no_analogue_reason: "",
        deviations: &[
            "Horizontal only; 1 DIP hairline in the border token (#E5E5E5 / white 10 %), snapped to one device pixel at every DPI — matches shadcn separator.",
        ],
        motion: "none (no shadcn motion for this use)",
    },
    Entry {
        key: "response",
        name: "Response / Content Surface",
        tier: 'A',
        status: Status::Implemented,
        sizing: Sizing::Stretchable,
        states: &["default", "copied", "follow-up"],
        shadcn: None,
        no_analogue_reason: "Mascot response composition (plain text + copy action + \
                             separator + follow-up composer) has no single shadcn analogue",
        deviations: &[
            "No shadcn analogue: plain text only (no Markdown), a ghost Copy icon button with a Copied state, then a separator and the follow-up composer inside one bubble.",
        ],
        motion: "none (no shadcn motion for this use)",
    },
    Entry {
        key: "badge",
        name: "Badge / Status Pill",
        tier: 'A',
        status: Status::Implemented,
        sizing: Sizing::ContentSized,
        states: &["default", "secondary", "outline"],
        shadcn: Some("badge"),
        no_analogue_reason: "",
        deviations: &[
            "Matches shadcn badge geometry: 22 DIP pill, 8 DIP horizontal padding, 12/500, 1 DIP border (transparent on default/secondary, border token on outline).",
            "Neutral variants only (default/secondary/outline); no destructive variant — status is carried by text, never by colour alone.",
            "Width differs from the reference only by glyph metrics (Segoe UI Variable vs Geist).",
        ],
        motion: "none (no shadcn motion for this use)",
    },
    // ---- Tier B (planned, NOT implemented) ----------------------------
    Entry {
        key: "scroll-area",
        name: "ScrollArea",
        tier: 'B',
        status: Status::Planned,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: Some("scroll-area"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "popover",
        name: "Popover",
        tier: 'B',
        status: Status::Planned,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("popover"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "dropdown-menu",
        name: "DropdownMenu / MenuItem",
        tier: 'B',
        status: Status::Planned,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("dropdown-menu"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "select",
        name: "Select",
        tier: 'B',
        status: Status::Planned,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("select"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "switch",
        name: "Switch",
        tier: 'B',
        status: Status::Planned,
        sizing: Sizing::Fixed,
        states: &[],
        shadcn: Some("switch"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "checkbox",
        name: "Checkbox",
        tier: 'B',
        status: Status::Planned,
        sizing: Sizing::Fixed,
        states: &[],
        shadcn: Some("checkbox"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "radio-group",
        name: "RadioGroup",
        tier: 'B',
        status: Status::Planned,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("radio-group"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "dialog",
        name: "Dialog / lightweight modal",
        tier: 'B',
        status: Status::Planned,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("dialog"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "settings-row",
        name: "Settings row",
        tier: 'B',
        status: Status::Planned,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: None,
        no_analogue_reason: "Mascot settings composition — planned, no product surface yet",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "progress",
        name: "Progress / activity indicator",
        tier: 'B',
        status: Status::Planned,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: Some("progress"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    // ---- Tier C (deferred) --------------------------------------------
    Entry {
        key: "accordion",
        name: "Accordion",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: Some("accordion"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "alert",
        name: "Alert",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: Some("alert"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "alert-dialog",
        name: "AlertDialog",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("alert-dialog"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "aspect-ratio",
        name: "AspectRatio",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Fixed,
        states: &[],
        shadcn: Some("aspect-ratio"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "avatar",
        name: "Avatar",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Fixed,
        states: &[],
        shadcn: Some("avatar"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "breadcrumb",
        name: "Breadcrumb",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("breadcrumb"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "calendar",
        name: "Calendar",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("calendar"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "carousel",
        name: "Carousel",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: Some("carousel"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "chart",
        name: "Chart",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: None,
        no_analogue_reason: "charting is out of the Mascot UI vocabulary",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "collapsible",
        name: "Collapsible",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: Some("collapsible"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "command",
        name: "Command palette",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("command"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "context-menu",
        name: "ContextMenu",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("context-menu"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "data-table",
        name: "DataTable / Table",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: Some("data-table"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "drawer",
        name: "Drawer",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: Some("drawer"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "hover-card",
        name: "HoverCard",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("hover-card"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "input-otp",
        name: "InputOTP",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("input-otp"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "menubar",
        name: "Menubar",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("menubar"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "navigation-menu",
        name: "NavigationMenu",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("navigation-menu"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "pagination",
        name: "Pagination",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("pagination"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "resizable",
        name: "Resizable panels",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: Some("resizable"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "skeleton",
        name: "Skeleton",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Fixed,
        states: &[],
        shadcn: Some("skeleton"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "slider",
        name: "Slider",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: Some("slider"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "sonner",
        name: "Sonner/toast system",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("sonner"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "tabs",
        name: "Tabs",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("tabs"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "toggle-group",
        name: "ToggleGroup",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("toggle-group"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "form",
        name: "full Form framework",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: Some("form"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "date-picker",
        name: "date/time picker",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::ContentSized,
        states: &[],
        shadcn: Some("date-picker"),
        no_analogue_reason: "",
        deviations: &[],
        motion: "n/a",
    },
    Entry {
        key: "card",
        name: "generic card library",
        tier: 'C',
        status: Status::Deferred,
        sizing: Sizing::Stretchable,
        states: &[],
        shadcn: Some("card"),
        no_analogue_reason: "generic card library deferred — Mascot Surface covers the \
                             one real product need",
        deviations: &[],
        motion: "n/a",
    },
];

/// Tier A lookup by machine key.
pub fn by_key(key: &str) -> Option<&'static Entry> {
    COMPONENTS.iter().find(|e| e.key == key)
}
